version: '3.9'
services:
  postgres:
    image: 'postgres:13'
    ports:
      - '5432:5432'
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasks
